//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
package MenuBTN;

import javax.swing.*;
import java.awt.*;

public class Shutdown extends JPanel {


    public Shutdown() {
        //construct components
        ImageIcon Shut = new ImageIcon("C:\\Users\\EvanJMcAfee\\Desktop\\OS\\Stage 2\\OS\\src\\MenuBTN\\OFF.png");
        ImageIcon H = new ImageIcon("C:\\Users\\EvanJMcAfee\\Desktop\\OS\\Stage 2\\OS\\src\\MenuBTN\\Hibernate.png");
        ImageIcon R = new ImageIcon("C:\\Users\\EvanJMcAfee\\Desktop\\OS\\Stage 2\\OS\\src\\MenuBTN\\Reboot.png");
        ImageIcon S = new ImageIcon("C:\\Users\\EvanJMcAfee\\Desktop\\OS\\Stage 2\\OS\\src\\MenuBTN\\Signout.png");
        JPanel jcomp1 = new JPanel ();
        JLabel d = new JLabel("What would you like to do?");
        JPanel jcomp2 = new JPanel ();
        JButton shutdown = new JButton(Shut);
        JButton hib = new JButton(H);
        JButton Restart = new JButton(R);
        JButton Sign = new JButton(S);
        //adjust size and set layout
        setPreferredSize (new Dimension (1000, 200));
        BoxLayout layout = new BoxLayout (this, BoxLayout.Y_AXIS);
        setLayout (layout);
        jcomp2.setLayout(new FlowLayout());
        //add components
        add (jcomp1);
        jcomp1.add(d);
        add (jcomp2);
        jcomp2.add(shutdown);
        jcomp2.add(hib);
        jcomp2.add(Restart);
        jcomp2.add(Sign);
    }


    public void openDialog() {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Shutdown());
        frame.pack();
        frame.setVisible (true);
    }
}
