//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!


import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;

public class volume extends JPanel {
    private JSlider volume;
    private JPanel sound;
    private JLabel img;
    public volume() {
        //construct components
        volume = new JSlider ();
        ImageIcon vol0 = new ImageIcon("C:\\Users\\EvanJMcAfee\\Desktop\\OS\\Stage 2\\OS\\src\\Vol0.png");
        ImageIcon vol1 = new ImageIcon("C:\\Users\\EvanJMcAfee\\Desktop\\OS\\Stage 2\\OS\\src\\Vol1.png");
        ImageIcon vol2 = new ImageIcon("C:\\Users\\EvanJMcAfee\\Desktop\\OS\\Stage 2\\OS\\src\\Vol2.png");
        ImageIcon vol3 = new ImageIcon("C:\\Users\\EvanJMcAfee\\Desktop\\OS\\Stage 2\\OS\\src\\Vol3.png");


        img = new JLabel();
        img.setIcon(vol2);
        //set components properties
        volume.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent event) {
                int value = volume.getValue();
                if (value == 0) {
                    img.setIcon(vol0);
                } else if (value > 0 && value <= 50) {
                    img.setIcon(vol1);
                } else if (value > 50 && value < 80) {
                    img.setIcon(vol2);
                } else {
                    img.setIcon(vol3);

                }
            }
        });

        //adjust size and set layout
        FlowLayout layout = new FlowLayout();
        layout.setHgap (5);
        layout.setVgap (5);
        setLayout (layout);

        //add components

        add(img);
        add (volume);
    }


    void vol () {
        int LOCH=(int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        int LOCW=(int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        JFrame frame = new JFrame ("MyPanel");
        frame.setUndecorated(true);
        KeyboardFocusManager.getCurrentKeyboardFocusManager().
                addVetoableChangeListener( "focusedWindow",
                        new VetoableChangeListener() {
                            private boolean gained = false;

                            @Override
                            public void vetoableChange( PropertyChangeEvent evt ) throws PropertyVetoException {
                                if ( evt.getNewValue() == frame ) {
                                    gained = true;
                                }
                                if ( gained && evt.getNewValue() != frame ) {
                                    frame.dispose();
                                }
                            }
                        });
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add(new volume());
        frame.setLocation(LOCW-209-20,LOCH-78);
        frame.pack();
        frame.setVisible (true);
    }
}
